name: Test Oracle sunf95

on:
  # Trigger the workflow on push or pull request
  #push:
  pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    #  - cron: '0 7 * * *'
    - cron: '0 7 * * *'  # Reduce the frequency until NORM is fixed.
  # Trigger the workflow manually
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

# Show the git ref in the workflow name if it is invoked manually.
run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual run {0}', inputs.git-ref) || '' }}


jobs:

  test:
    name: Run sunf95 tests
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        solver: [newuoa, cobyla, lincoa, bobyqa, uobyqa]
        # As of 20230213, -fast fails often; seems due to stack overflow. How to force sunf95 to use
        # heap only?
        fflags: [-O1, -O2, -O3, -g] #, -fast]
        testdim: [small, big]

    steps:

      - name: Run `sudo apt update -y`
        run: sudo apt update -y  # Otherwise, free-disk-space or other actions relying on `apt` may fail

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # all of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false  # Important, or the runner may be shut down due to memory starvation.

      - name: Clone Repository (Latest)
        uses: actions/checkout@v5.0.0
        if: github.event.inputs.git-ref == ''
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
          submodules: recursive
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v5.0.0
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Install Oracle sunf95
        run: bash .github/scripts/install_sunf95

      - name: Revise Makefile.common to exclude r16 tests when the dimension is big
        if: ${{ matrix.testdim == 'big' }}
        shell: bash
        run: |
          cd fortran/tests/makefiles || exit 42
          $SEDI 's|\$(TST)_.*r16_d[0,1]_tst||g' Makefile.common && cat Makefile.common

      # - name: Revise bign
      #   run: |
      #     cd fortran/tests
      #     $SEDI 's|::\s*bign\s*=.*$|:: bign = 200_IK|' test_lincoa.f90

      - name: Conduct the test
        run: |
          export FFLAGS=${{ matrix.fflags }}
          export TESTDIM=${{ matrix.testdim }}
          IK=i$(( 2**(1 + $(date +%-d) % 3) ))
          echo "IK=${IK}"
          echo "IK=${IK}" >> "$GITHUB_ENV"
          cd "$ROOT_DIR"/fortran/tests && make stest_${IK}.${{ matrix.solver }}
          # sunf95 cannot handle matrix indexing with TRUELOC or allocatable characters.
          # cd "$ROOT_DIR"/fortran/examples/${{ matrix.solver }}
          # export EXAMPLE_NUM=1 && make clean && make stest
          # export EXAMPLE_NUM=2 && make clean && make stest

      - name: Store artifacts
        uses: actions/upload-artifact@v4.3.1
        if: always()  # Always run even if the workflow is canceled manually or due to overtime.
        with:
          name: ${{ matrix.solver }}-${{ env.IK }}-${{ matrix.fflags }}-${{ matrix.testdim }}
          path: ${{ env.TEST_DIR }}/prima/fortran/tests/test.${{ matrix.solver }}/log/*.log

      - name: Remove the test data
        if: always()  # Always run even if the workflow is canceled manually or due to overtime.
        run: rm -rf ${{ env.TEST_DIR }}

  # The following job check whether the tests were successful or cancelled due to timeout.
  # N.B.: Remember to specify `continue-on-error: true` for the job of the tests.
  check_success_timeout:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs: test
    steps:
      - name: Clone the GitHub actions scripts
        uses: actions/checkout@v5.0.0
        with:
          repository: equipez/github_actions_scripts
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_ACT }} # This forces checkout to use SSH, not HTTPS
          path: scripts

      - name: Check whether the tests were successful or cancelled due to timeout
        run: bash scripts/check_success_timeout_big_test ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.run_id }}
